@url=http://localhost:8000/api/
@token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDI5OTUzNX0.qOyxTJDXjf_CGwhKOINxRVfUrPuFQkVdDOVCEw4ILC4
#GET ALL PROJECTS
GET {{url}}projects/

###

#GET A SINGLE PROJECT
GET {{url}}projects/2/


###

#DELETE A PROJECT
DELETE {{url}}projects/7/
content-type: application/json
Authorization: Bearer {{token}}

###

#CREATE A PROJECT
POST {{url}}projects/
content-type: application/json
Authorization: Bearer {{token}}

{
  "projectName":"new Project10",
  "url":"http://www.google.com",
  "projectType": [4]
}


###
#CREATE A NEW USER
POST {{url}}auth/register/
content-type:application/json

{
"username":"brad",
"email":"brad@email.com",
"password":"pass",
"passwordConfirmation":"pass"
}

###
#LOGIN USER
POST {{url}}auth/login/
content-type:application/json

{
  "email":"brad@email.com",
  "password":"pass"
}

###
#MAKE A COMMENT 

POST {{url}}projects/2/comments/
content-type: application/json
Authorization: Bearer {{token}}

{
  "content":"this is a comment that im gonna delete (craig)"
}

###
#DELETE COMMENT

DELETE  {{url}}projects/8/comments/9/
content-type: application/json
Authorization: Bearer {{token}}













