@url=http://localhost:8000/api/
@token= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjUsImV4cCI6MTYyNDI5MDI2NH0.ZvsqMPawOhFrdEYKZXhsedFPQpoZcgPFxmx6GnosO0w
#GET ALL PROJECTS
GET {{url}}projects/

###

#GET A SINGLE PROJECT
GET {{url}}projects/4/


###

#DELETE A PROJECT
DELETE {{url}}projects/5/
content-type: application/json
Authorization: Bearer{{token}}

###

#CREATE A PROJECT
POST {{url}}projects/
content-type: application/json
Authorization: Bearer {{token}}

{
  "projectName":"new Project10",
  "url":"http://www.google.com"
}


###
#CREATE A NEW USER
POST {{url}}auth/register/
content-type:application/json

{
"username":"clem",
"email":"clem@mail.com",
"password":"pass",
"passwordConfirmation":"pass"
}

###
#LOGIN USER
POST {{url}}auth/login/
content-type:application/json

{
  "email":"clem@mail.com",
  "password":"pass"
}

###
#MAKE A COMMENT 

POST {{url}}projects/4/comments/
content-type: application/json
Authorization: Bearer {{token}}

{
  "content":"this is a comment to test before i push!"
}












