# Generated by Django 3.2.4 on 2021-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_project',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
