# Generated by Django 3.2.4 on 2021-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_user_gacohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='GAcohort',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
