# Generated by Django 3.2.4 on 2021-06-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_alter_user_gacohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='GAcohort',
            new_name='gacohort',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='GitHub',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LinkedIn',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Twitter',
            new_name='twitter',
        ),
    ]
