# Generated by Django 3.2.4 on 2021-06-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20210618_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personal_site',
            new_name='personalsite',
        ),
    ]
