# Generated by Django 3.2.4 on 2021-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_expo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ManyToManyField(blank=True, related_name='project', to='project_expo.Project_type'),
        ),
    ]
