# Generated by Django 3.2.4 on 2021-06-14 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_expo', '0002_rename_project_type_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
