# Generated by Django 3.2.4 on 2021-06-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_expo', '0003_auto_20210614_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Url',
            new_name='url',
        ),
    ]
