# Generated by Django 3.2.4 on 2021-06-15 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_expo', '0004_rename_favorited_by_project_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favorited_By',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
